config/routes.rb
Rails.application.routes.draw do
  resources :book_sites
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book_site.rb
class BookSite < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_sites_controller.rb
class BookSitesController < ApplicationController
  before_action :set_book_site, only: [:show, :edit, :update, :destroy]

  # GET /book_sites
  # GET /book_sites.json
  def index
    @book_sites = BookSite.all
  end

  # GET /book_sites/1
  # GET /book_sites/1.json
  def show
  end

  # GET /book_sites/new
  def new
    @book_site = BookSite.new
  end

  # GET /book_sites/1/edit
  def edit
  end

  # POST /book_sites
  # POST /book_sites.json
  def create
    @book_site = BookSite.new(book_site_params)

    respond_to do |format|
      if @book_site.save
        format.html { redirect_to @book_site, notice: 'Book site was successfully created.' }
        format.json { render :show, status: :created, location: @book_site }
      else
        format.html { render :new }
        format.json { render json: @book_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_sites/1
  # PATCH/PUT /book_sites/1.json
  def update
    respond_to do |format|
      if @book_site.update(book_site_params)
        format.html { redirect_to @book_site, notice: 'Book site was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_site }
      else
        format.html { render :edit }
        format.json { render json: @book_site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_sites/1
  # DELETE /book_sites/1.json
  def destroy
    @book_site.destroy
    respond_to do |format|
      format.html { redirect_to book_sites_url, notice: 'Book site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_site
      @book_site = BookSite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_site_params
      params.require(:book_site).permit(:title, :page_count, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_sites_helper.rb
module BookSitesHelper
end

app/views/book_sites/_form.html.erb
<%= form_with(model: book_site, local: true) do |form| %>
  <% if book_site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_site.errors.count, "error") %> prohibited this book_site from being saved:</h2>

      <ul>
        <% book_site.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :page_count %>
    <%= form.text_field :page_count %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_sites/edit.html.erb
<h1>Editing Book Site</h1>

<%= render 'form', book_site: @book_site %>

<%= link_to 'Show', @book_site %> |
<%= link_to 'Back', book_sites_path %>

app/views/book_sites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Sites</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Page count</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_sites.each do |book_site| %>
      <tr>
        <td><%= book_site.title %></td>
        <td><%= book_site.page_count %></td>
        <td><%= book_site.rating %></td>
        <td><%= link_to 'Show', book_site %></td>
        <td><%= link_to 'Edit', edit_book_site_path(book_site) %></td>
        <td><%= link_to 'Destroy', book_site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Site', new_book_site_path %>

app/views/book_sites/new.html.erb
<h1>New Book Site</h1>

<%= render 'form', book_site: @book_site %>

<%= link_to 'Back', book_sites_path %>

app/views/book_sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book_site.title %>
</p>

<p>
  <strong>Page count:</strong>
  <%= @book_site.page_count %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @book_site.rating %>
</p>

<%= link_to 'Edit', edit_book_site_path(@book_site) %> |
<%= link_to 'Back', book_sites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>